### ISSUE TITLE
JIRA: An error occurred

### ISSUE THREAD

**Issue by minghsieh-prenetics** [hiptest/hiptest-issue-tracker#107]
### Steps to reproduce
1.  Go to any Boards, wait few minutes after it loading or click any issue / task, the dialog "An error occurred" should popup.

### Expected behaviour
No popup should be shown

### Actual behaviour
<img width="1916" alt="screen shot 2018-04-12 at 11 42 33 am" src="https://user-images.githubusercontent.com/33742463/38655422-19141436-3e47-11e8-817d-fe976c49385a.png">

### My configuration
**Browser:**
Have tried:

- Safari
- Google Chrome
- Firefox

All have the same issue.

**Operating system:**
macOS High Sierra
Version 10.13.4

**Hiptest product line info:**
Hiptest plugin for JIRA
Version: 1.2.2
Vendor: Hiptest
Add-on key: hiptest.jira-plugin

**Comment by karamosky** [comment]
Hello @minghsieh-prenetics 
This issue is due to our last domaine name changes.
All you need to do is to update the Hiptest url from the Hiptest Jira plugin page.
On the Hiptest JIRA plugin, click configure then change the URL from https://hiptest.net to https://**app**.hiptest.**com**
Regards
Karam

**Comment by minghsieh-prenetics** [comment]
Seems working. Close for now. Thanks.
