### ISSUE TITLE
UIDs showing up in HipTest Publisher output

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#12]
When I download my feature specs using HipTest Publisher's SAAS interface, the feature files retrieved have UIDs appearing in the scenario names and and scenario outline example rows:

```
  Scenario Outline: Validate Nav Links on Home Page (uid:4127a335-46f8-4f11-9236-8e550a86cbb3)
    Given that I am on the "<SITE_NAME>" "home" page
    When I hover over the "<NAV_LINK>"
    Then I should see the "<SUBNAV_MENU>"
    When I click the "<NAV_LINK>"
    Then I should go to the "<SITE_NAME>" "<DESTINATION>" page

    Examples:
      | SITE_NAME | NAV_LINK | SUBNAV_MENU | DESTINATION | hiptest-uid |
      | chron | local nav link | local subnav menu | local section | uid:b9acb6ac-700d-4967-b9ae-61921e7a125f |
```

The table row UID is no big deal; it's a column I can just ignore.  But the UID appearing in the scenario name is a problem for me, because my application is parsing these files and the scenario names are used to generate output log file names.  What is that UID doing there, and can I switch it off somehow?

**Comment by vincent-psarga** [comment]
Hi,

The UIDs are there so we can match which test correspond to which scenario when pushing the results back to Hiptest (relying only on the name could be used with Cucumber as we do not do any modification of the name, but for other languages we have to make modifications on the scenario names and UID is the only reliable option).

We already have the possibility in Hiptest to match by name, which could be used with Gherkin I guess. So that could be an extra option of Hiptest-publisher to avoid exporting the UIDs even when generating from a test run.
I'll add that to the backlog and discuss it with the team.

**Comment by vincent-psarga** [comment]
I've added an option to hiptest-publisher (and also the SaaS version) that do not output the UIDs (in scenario name + the column in the examples).

![screen shot 2016-06-23 at 11 40 19](https://cloud.githubusercontent.com/assets/186248/16298828/91fbfad8-3937-11e6-8aad-12c8918147b0.png)

**Comment by adamlacoste** [comment]
Thanks Vincent!
