### ISSUE TITLE
Feature Request: Being able to filter tests on JIRA fields

### ISSUE THREAD

**Issue by PierreFrancois-1** [hiptest/hiptest-issue-tracker#149]
Hi
Following up on my topic below, I'd like to request a new feature.
https://community.hiptest.com/t/create-test-runs-based-on-a-query-in-jira/1618/3

**Context:**
We user JIRA to track our user stories throughout releases. Therefore, each JIRA ticket has a custom field containing the version in which it will be delivered.
We use Hiptest for testing and we have one test run per version. 
All our Hiptest tests are linked with JIRA tickets.

**Request Background:**
At the moment, when creating a test run for a version in hiptest, we need to manually fetch all our test cases and add them to the test run of the version. This is a tedious job and we would like to "automate" it, at least partially.

**Requirements**
The feature I request is to be able to filter tests based on the JIRA tickets they are linked to.
Example: Fetch all tests which are linked to a JIRA ticket for which the field "field name" = "field value"

Thank you

**Comment by HoudaDabou** [comment]
Hi @PierreFrancois-1,

Our team has made many improvements on our add-on available since Jira.

Now from the HipTest traceability matrix, you can view your Jira issues related to your HipTest projects according to your customized filters, as shown here:

![jira_issue_public](https://user-images.githubusercontent.com/43133237/53515864-47ddc880-3acb-11e9-90c9-f7155ca5ebbb.png)

Thus, this feature can meet your needs.

Feel free to ask us more details.

Regards,
Houda
