### ISSUE TITLE
Notification received for being over user limit, although the additional user role = Reader

### ISSUE THREAD

**Issue by fjanes-at-amadeus-dot-com** [hiptest/hiptest-issue-tracker#150]
### Steps to reproduce
1. Add a user role as Reader only, where the total user number is over the license limit.

### Expected behaviour
To be advised

### Actual behaviour
Notification was received that we are over the limit of users.

Note, we need to verify that we are not being billed for additional users extended to customers who have reader roles only. 

Note, initial review was initiated by email with support and 
christophe.bliard@hiptest-7.intercom-mail.com
but with no further response, I trust filing this issue for review is best.

### My configuration
Firefox 61.0.1  64-bit

**Operating system:**
Windows 7 Enterprise

**Comment by cbliard** [comment]
Hi Franc,

When adding a new user, Hiptest checks the number of users with 'Member' role and your license limit and send emails if necessary. First emails notify you are close to the limit, and further emails notify you need to upgrade. We do not block adding additional users and trust you to contact us to upgrade your account. Note that this behavior may change in the future.

So you have a 10 users pack:
 * When adding the 8th user with member role, you receive an email with subject: _Hiptest: limit close to be reached! 2 seats remaining in [...] organization_
 * When adding the 9th user with member role, you receive an email with subject: _Hiptest: limit close to be reached! One seat remaining in [...] organization_
 * When adding the 10th user with member role, you receive an email with subject: _Hiptest: limit reached! No more seat available in [...] organization._
 * When adding a 11th user with member role, you receive an email with subject: _Hiptest: we noticed that you have too many users in your [...] organization. [...] To fit your number of users with your usage, you have to upgrade your account._

You can then give role Reader to the 11th user, but the mail is already sent. That's why you are observing this behavior.

We will fix this in a future version by letting the role choice at user invitation.

Does it answer your question?

**Comment by fjanes-at-amadeus-dot-com** [comment]
Thanks for the detailed info.
If there is no additional billing for the 10+ users only be readers, then we are good.

**Comment by cbliard** [comment]
Great! I'll close this ticket. Feel free to reopen it if you have any other questions on this topic.
