### ISSUE TITLE
HipTest crashes when selecting BDD with a project that has test already written; automation then broken

### ISSUE THREAD

**Issue by mm3599** [hiptest/hiptest-issue-tracker#16]
Ubuntu 14.04

1) Create a project
2) Write tests for that project
3) Do a test execution
4) Turn on 'BDD'
5) Go back to the project
6) Go back to the BDD configuration section - the ID is unchecked
7) Then HipTest crashed

Attaching logs

[replicated-support471975153.tar.gz](https://github.com/hiptest/hiptest-issue-tracker/files/374574/replicated-support471975153.tar.gz)

**Comment by cbliard** [comment]
How did it crash? Did it stop working? Did you get an error message?

**Comment by mm3599** [comment]
Yes – it stopped working and kicked me out; and gave a strange error.
I had to login again.

I can’t enable BDD for the first project.

**Comment by cbliard** [comment]
According to the logs, you logged out from Hiptest at some point, then you used Hiptest but I do not see any login. What I see is a lot of requests that are unauthorized. This is normal as you logged out. 

My guess is that you had multiple browser tabs, you signed out from one browser tab, and you used the other one that still had Hiptest opened.

If my guess is true, the bug is that Hiptest should detect that you are signed out and redirect you automatically to the sign-in page. We'll investigate for this.

Thank you for your feedback.

**Comment by aurelien-reeves** [comment]
The issue should be fixed now.
We deploy a fix that show a message to all clients of a user when he has been logged out on the server.
