### ISSUE TITLE
Update existing folder content from .feature file

### ISSUE THREAD

**Issue by IvanK-01** [hiptest/hiptest-issue-tracker#172]
I'm trying to update existing folder using 
https://hiptest.github.io/slate/#create-from-feature
But the API call returns 409 error with error text: "Failed. Response message = A folder named Sub 10 already exists."
Could you fix this error or add another API to update existing folder?

**Comment by HoudaDabou** [comment]
Hi,

We have taken into account your request. Unfortunately this feature isn't available now, please refer to the API documentation [here](https://hiptest.github.io/slate).

This latter contains all information about all available features. If one or more options are not listed, it is because our teams are developing them or they are listed in our Trello backlog in the part named "REST API" [here](https://trello.com/b/sSdBSlL0/cooking-up-for-the-coming-months).

Thank you for your understanding :slightly_smiling_face: 

Regards,
Houda
