### ISSUE TITLE
Parameters from dataset are not escaped

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-issue-tracker#195]
### Steps to reproduce
1. Create a scenario with a dataset
2. Add a json value in this dataset like { "key" : "val" }
3. Generate the code with the publisher (java-junit)

### Expected behaviour
To have an escaped parameter like "{ \\"key\\" : \\"val\\" }"

### Actual behaviour
No escape, as the consequence it does not compile.

### My configuration
**Browser: ** --

**Operating system:**
Debian

Please note that the escaping works for simple parameters, but fails for parameters coming from a dataset.

**Comment by HoudaDabou** [comment]
H @ylacaute,

May you tell us which version of hiptest-publisher do you work with?

Just executing this following command line and publish the output:

`hiptest-publisher -v`

**Comment by ylacaute** [comment]
Hi, I used the docker version of the master branch of hiptest-publisher (cloned few days ago).
I can give you more info Monday, I will updat this post.

**Comment by HoudaDabou** [comment]
thank you, so if you use the docker version , it's not necessary to send the output :) 

To meet your need, you may override hiptest-publisher templates, or add a [node modifier](https://github.com/hiptest/hiptest-publisher/tree/master/lib/hiptest-publisher/node_modifiers)...

But I'm not sure because your issue is a little bit complicated, the difficulty lies in the fact to want to add an escape character into the parameter value { "key" : "val" }

I'll ask @vincent-psarga (our hiptest-publisher expert) from Monday and get back to you ASAP!

**Comment by ylacaute** [comment]
Fixed
