### ISSUE TITLE
Improvement: BA should be able to add entry in hiptest itself instead of JIRA

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#2]
Hi,

As per your webinar "Webinar: Kick start your project in BDD with Hiptest"  ,  new story is added in JIRA view.

Later it will be shown as linked in hiptest and scenarios need to be added this.

Instead of 2 views , why can't BA/PM/ Marketing person can add story in hiptest itself. This will save shifting between 2 windows and flow will be much clearer

Also this makes it mandatory to buy JIRA license to use hiptest

Please review

Thanks & Regards,
Vikram

**Comment by vincent-psarga** [comment]
Hi Vikram,

The process shown in the webinar is just a proposed process, not anything mandatory. Marketing people could easily have an Hiptest account and create the new features there instead of Jira.

We just thought this would be the most plausible process (we shown it in Jira but it could be Trello or any other tool) and it allowed us to show how results where later on displayed in Jira, but it's always possible to adapt it based on the needs of the company (for example using Trello instead of Jira or any other tool).

Best regards,
Vincent
