### ISSUE TITLE
Select which JIRA fields to display in Hiptest JIRA integration

### ISSUE THREAD

**Issue by frsta** [hiptest/hiptest-issue-tracker#23]
With the latest implementation (https://trello.com/c/fGZVAIGX/237-option-add-more-jira-fields-when-creating-and-issue-from-hiptest) Hiptest displays all mandatory fields but I want to be able to select which fields I want to be displayed not only mandatory fields.

**Comment by cbliard** [comment]
Sounds fair :+1: 

Adding mandatory fields was our priority because it could prevent some users to create issues from Hiptest. Now that we support mandatory fields, adding optional ones should be easy. I created [another Trello task for it](https://trello.com/c/6ZA98DYO/284-when-creating-a-jira-issue-be-able-to-configure-any-fields). You can vote for it!
