### ISSUE TITLE
An error has occurred, sorry for the inconvenience - while creating a new scenario

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#3]
https://hiptest.net/app#/projects/16871/testPlan/folders/56493/newScenario

1. After entering a sentence and clicking on Create button , got error "An error has occurred, sorry for the inconvenience"

**Comment by vincent-psarga** [comment]
Hi,

By any chance, did you have the chance to see any error shown in the javascript console ? I guess you had the message shown on the full page ?
It sometimes happens when the client version of the code and the server one are not synced (reloading solves the issue).

I'll have a look at the logs to try to understand what happened.

Best regards,
Vincent

**Comment by vikramvi** [comment]
Tried to reproduce this issue but now it's working fine. Earlier there was no error on FF console
