### ISSUE TITLE
"Run in current execution cycle" button is confusing ( UX ) 

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#49]
![run_in_current_execution_cycle](https://user-images.githubusercontent.com/308490/31673716-3fe5eb42-b360-11e7-87f4-14675d759dc3.png)

- refer to attached screen shot
- user is already in a test execution cycle
- still user is shown button on top stating "Run in current execution cycle"
- this is confusing UX

**Comment by cbliard** [comment]
Thank you for reporting this.

This button is here to show the same window you get when clicking "Resume" on the left, but focused on this test instead of being focused on the first unexecuted test. 

You are right, this is confusing as the user can also set the status directly on the same screen. We'll review that and keep you informed about our thoughts.

**Comment by HoudaDabou** [comment]
H there,

To date, HipTest team has developed a new design with better features, feel free to discover it!

Regards,
