### ISSUE TITLE
Even when tag is present against scenario; Select tag dropdown is empty

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#54]
![metrics_page](https://user-images.githubusercontent.com/308490/31708986-ebe1608a-b3f0-11e7-88ca-dd7129db35c3.png)
![tag_against_scenario](https://user-images.githubusercontent.com/308490/31708987-ec02b898-b3f0-11e7-8381-8eba97abfb85.png)

- I've added some tags against the user scenarios
- Later went to Project metrics page
- Select tag drop down is showing blank.

**Comment by vikramvi** [comment]
@cbliard ping

**Comment by cbliard** [comment]
This issue is rather an UX issue. Tags can be valued. Key and value are separated with a colon for example, you can have "execution: manual", "execution: automated" and "execution: exploratory". 

From the metrics, you can create two kind of charts. 
 1. First choice, "Based on tag key", compares multiple values of all tags having the same key. So in this example, you select "execution" and you'll see a pie chart of each different values across the scenarios.
 2. Second choice, "Compare multiple tags", does a pie charts on multiple tag keys you have selected.

In your example, you can't select any tags because you chose "Based on tag key" and you don't have any valued tags. You should select "Compare multiple tags".

Does it work as you expected?

**Comment by vikramvi** [comment]
@cbliard Thanks for review but it's not clear yet

- How to add value to tag ?
- My understanding is that tag will have single string @automation @manual etc per Gherkin syntax
- Where, how & why a QA will add value to a tag ?
- Any example of this can be easy to understand
- Also the drop down "Add new chart" says "Based on tag key" and doesn't mention about value 

per me this is both UX and functional issue.

**Comment by cbliard** [comment]
@vikramvi Syntax of a tag is "key: value". key is alphanumeric (no spaces). value can be anything.

Here are some examples of valued tags and not valued tags:
- some valued tags
 - priority: high
 - priority: medium
 - priority: low
 - platform: iOS
 - platform: Android
 - device: Samsung Galaxy Note 7
 - device: Google Nexus 4
 - JIRA: ABC-123
 - github-issue: 56
 - automated: yes
 - automated: no
 - ...
- some plain tags:
 - automated
 - manual
 - bug
 - to_be_reviewed
 - invalid
 - next_release
 - ...

Then these tags can be used to select scenarios to create test runs, to [make custom links to external tool](https://docs.hiptest.net/enable-fast-links-with-tags/), to [create pie charts based on them](https://docs.hiptest.net/generating-metrics/) or you can roll out your own tool by using our [REST API on tags](https://hiptest.github.io/slate/#tags). Tagging is a tool. Use it where you see value.

When we export to Gherkin, we have to map them to a syntax that works for Gherkin, so we normalize them. A tag like `myTag: some value` will become `@myTag-some_value`as shown in [hiptest-publisher renderer unit tests](https://github.com/hiptest/hiptest-publisher/blob/master/spec/render_shared.rb#L1034). This can be [overriden by customizing templates](https://blog.hiptest.net/2017/03/02/customising-your-export-with-hiptest-publisher-part-i-understanding-handlebars/).

You are right, "Based on tag key" is not a good wording. We'll agree on a new term and change that.
