### ISSUE TITLE
Given When Then under Edit section shown differently

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#57]
![given_when_then_1](https://user-images.githubusercontent.com/308490/31710293-d61dacdc-b3f4-11e7-8782-798bb797ef42.png)
![given_when_then_2](https://user-images.githubusercontent.com/308490/31710294-d67eb946-b3f4-11e7-9e89-0c6f7d63a5e0.png)

- Refer to above 2 screen shots
- Given When Then keywords are shown differently in each of the scenarios
- In one screen show there is "wrench" icon in the left
- 2nd screen shot has got Given keyword in BOLD and COLORED, this is confusing

**Comment by vikramvi** [comment]
@cbliard ping

**Comment by cbliard** [comment]
Thanks for reporting.

This is not a bug. In first scenario, steps are plain action/result steps, as denoted by the wrench icon. In second scenario, it is an action word that is getting called and it has a bold colored annotation.

They have the same text but are rendered differently because one is a plain step, the other one is an action word call. 

This can be improved. In which way can we make it less confusing for you?

**Comment by vikramvi** [comment]
@cbliard Thanks for review but still I'm not clear about different between "plain action/result step" vs "action scenario"

In Gherkin syntax there is no such things, so I'm bit confused here.
Please clarify when to use each of these terms and in which situation ? It's not pretty clear

**Comment by cbliard** [comment]
@vikramvi I understand that you have a Gherkin background where you want to describe the behavior of your app with examples. The Act-Arrange-Assert pattern is done using Given-When-Then to have a more natural tone yet keeping it formal. It's a [business-readable DSL](https://martinfowler.com/bliki/BusinessReadableDSL.html).

Some other people will want to write test scripts and perform steps and expect a result. The testing flow will more be do this, do that, do this, check that, do that now, check this, and so on.

I would use the Given/When/Then approach to communicate with other teammates about the expected behavior of my application in a high level way.

I would use bare action/result steps when I want to perform some steps one by one and check a specific outcome. I tend to favor them when doing some weird bug reproduction tests where the test can't be a description of the app behavior but rather a sequence of steps that puts the app in a state where a bug arise. We can hardly write "When doing that weird thing Then no bug should happen". YMMV.

Does it sound better for you?

**Comment by vikramvi** [comment]
@cbliard  Thanks for detailed clarification. Only concern is to keep is simple for everyone using the tool and no need to add more complexities
