### ISSUE TITLE
hiptest repo showcasing API and UI tests it runs in real time

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#6]
@vincent-psarga  I feel it will be nice if you guys publish UI and API test stories in default projects.

It will be more useful for users to learn about tool , how you guys use it in day to day life and how they can use in their project.

Others can contribute to your repos as well and do self learning with that.

Thanks

**Comment by vincent-psarga** [comment]
That's something planned (and partially done).

For UI testing, we have a few blogposts describing tests with Selenium, Calaba.sh or Appium. All those are using public Github repositories to help understand. You can already access those blogpost from the automation page in a Hiptest project.

What we are planning to add, in order to help users with testing, is to add the possibility to request a project "Coffee machine" that we use with all our repositories named hps-<language>-<framework>. The idea will be for the user to be able to simply play with hiptest-publisher with a project they can easily manipulate (and for which all the useful code is already available in all the languages supported by our publisher).
It's not exactly API samples but comes pretty close to it.

We might write a new blogpost dedicated to API testing, that would help.

**Comment by vikramvi** [comment]
Thanks , I will love to see these changes and contribute as well.
