### ISSUE TITLE
Users who are part of organization should get automatic access to all the project under that org

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#60]
### Steps to reproduce
1.   Invite user/s to organization under https://hiptest.net/app/organizations/xxxx
2.   User accepts the invite and be part of that org.
3.  Now create project under that organization

### Expected behaviour
1. newly created project should be shared with all the users under that particular organization.
2. This is quite confusing that one needs to invite already existing users under org to a project.

### Actual behaviour
1. Newly created project is not shared with anyone except the current user

### My configuration
**Browser:**  
NA

**Operating system:**
NA

**Comment by jracenet** [comment]
Hey @vikramvi :-)

We didn't want projects to be automatically shared with all the organization members, in order to avoid an user to have a unmaintainable list of projects, since every users can have their default samples projects and to be assigned to multiple organizations (which means a LOT of projects!)

However, when we first designed the organizations system, our intention was to introduce a concept of teams, to allow -for example- the behaviour your describe ("I am part of team T1, so I am directly able to access to every projects that have been assigned to this team"). To be honest, we did not had the time to get back to this topic for now (even if we are going to work on the organization/billing system this quarter).

In the meanwhile, I think that improve the project creation process, with the addition of the possibility to directly add some/all/none users of the organization you're part of could be an answer to your need (and could be planned and released more quickly than the team system).

What do you think about it?
