### ISSUE TITLE
Query : Keeping user stories in sync with github repo ?

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#8]
In my project , we have a center repo which works as submodule for multiple automation projects.

In this case , how can I keep hiptest user stories in sync with github repo for stories ?

Individual automation repos ( web , mobile ) , read stories from submodule and execute them.

Is there any nice way to keep whole flow of hiptest -> github in sycn ?

Thanks,
Vikram

**Comment by vincent-psarga** [comment]
Hi,

I'm not sure I fully understood your use case. From what I understand (correct me when I'm wrong):
 - you have a single Hiptest project
 - you have multiple repositories for automation
 - you do not execute the same tests in each repo (that one is a guess)

The best in that case is to have one test run for each automation repo and let the CI tool fetch the tests from the correct test run.
It would also be possible to store the scenarios from those test run in your github repository (for example with a cron tab that could update & commit the tests every night) but I would not recommend this solution (keeping the tests from a test run in the repository is not that practical when it comes to automate new tests ...).

That said, it's better, from my experience, to only let human commit the changes to the tests. Most of the time, you'll need a new action word to be implemented or a small change here and there (because even if the action word is already implemented, it'll have to behave a bit differently in that new test). From Hiptest experience, even with a lot of already implemented action words, it's pretty rare to have a test automated directly after writing it.

**Comment by vikramvi** [comment]
@vincent-psarga  let me give some real world scenario

1. As a tester I need to automate "hiptest" s/w on web , android and iOS clients.
2. I use GitHub as configuration management tool
3. I write user stories applicable to all the platforms in "hiptest"
4. For each of the clients ( web , android , iOS ) , I've separate repository.

Queries:
1. Without "hiptest" , I will maintain user stories in unique repo. This repo will be used as sub-module in each of the individual clients' automation repo.
2. With hiptest , how can I manage flow mentioned in step 1 ?


Please clarify

**Comment by vincent-psarga** [comment]
Hi,

So, my advice for your use case would be to keep the idea of the sub-module github repo. In this repo, your should only publish the tests (using the --only=tests option of hiptest-publisher, or --only=features,step_definitions if you use a Gherkin based syntax).
In your client repositories, you include this repository as a sub-module and you implement the action words as needed for your client (once again using hiptest-publisher).

When a new scenario is added (or an existing one is modified), simply use hiptest-publisher in the common repository to generate the new code for the tests and commit the changes.
Then, for each client repository, update the submodule (as you would have done previously) and update the action words if needed (as explained in this documentation): https://github.com/hiptest/hiptest-publisher/blob/master/docs/upgrading_actionwords.md

For the question of the CI, Hiptest integrates pretty nicely with CI tools. Basically, the idea will be the following:
 - create a test run dedicated to the CI
 - when a scenario/test has been automated for all the clients, add it to this test run
 - in the CI task, before running the tests, upgrade them using hiptest-publisher so it will fetch only the tests in this test run (it is the same command line than for generating the tests with an extra option: "--test-run-id=1234", where 1234 is the ID of your test run)
 - run the tests as you usually do
 - push the results back using hiptest-publisher again

We have some doc about that here: http://docs.hiptest.net/integrate-with-your-continuous-integration-process/ and also some Webinars about automation/CI available on our Youtube channel if you haven't seen them yet: https://www.youtube.com/watch?v=MMegmqaEdWE

That said, in your use case, I would create one test run for each client (and, same principle, add the test to this test run when the automation is ready for this particular client).
The reason for that is that it will be easier for you to know on which platform a test failed. We plan to add information about environment to the test runs (to fit your exact test case) but that's not available yet.

I hope the answer is clear, do not hesitate to ask for more precision.

**Comment by vikramvi** [comment]
Hi Vincent,

Thanks a ton for detailed info.

I will try these out and get back / update back with queries / info.

For now closing this issue.

Regards,
Vikram
