### ISSUE TITLE
Test run page. Selecting any option from upper breadcrum navigation removes scenarios from main view

### ISSUE THREAD

**Issue by leandro-chescotta-olx** [hiptest/hiptest-issue-tracker#89]
### Steps to reproduce
1. Access a test run with some subfolders and some scenarios in them.
2. Access a subfolder.
3. Return to the main view using the navigation breadcrum.

### Expected behaviour
The view should show the list of scenarios, and the user could filter between the different results ("Not Run", "Failed" or "Skipped")

### Actual behaviour
No scenarios are showed, and the user have to re-enter the test run for them to show again.

### My configuration
Google Chrome
MacOs X

**Comment by severinedarlot** [comment]
Hello Leandro, 
In fact, this is the expected behavior because when you click on the navigation breadcrum you are redirected on the root folder page and no to the test run main view. The folder page shows only the tests of this folder. To return on the main view, you should click on the title of the test run at the left up.
I hope this helps you.
