### ISSUE TITLE
Hiptest constantly logs me out

### ISSUE THREAD

**Issue by christianbaumann** [hiptest/hiptest-issue-tracker#96]
### Steps to reproduce
1. Work with Hiptest
2. Use right-mouse-click/ open-link-in-new-tab to open a scenario in a new tab

### Expected behaviour
Scenario opens in a new tab

### Actual behaviour
In the new tab I have to login

### My configuration
**Browser:** Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Operating system:** Windows 8.1 Enterprise

**Comment by christianbaumann** [comment]
Seems to be cause by the integration with JIRA ([Integration with Jira not working properly](https://github.com/hiptest/hiptest-issue-tracker/issues/97)), so closed this one.

**Comment by aurelien-reeves** [comment]
Actually I guess this is the issue, and the other one because of it.

Could you please try closing all your tab / browsers - at least all the Hiptest ones - clearing your history and cookies, then open a new tab on hiptest, sign-in, and check if you still are disconnected after some time?

**Comment by christianbaumann** [comment]
Cleared history, cookies, and so on...
Working with Hiptest then seems to be fine, but as soon as Jira comes into play, I face the same issues again.

**Comment by cbliard** [comment]
Hi Christian,

I'm trying to reproduce your issue. Do you observe the same behavior with another browser or with private navigation?

**Comment by christianbaumann** [comment]
On the same machine it works using IE 11 and Firefox 58.

On another machine (Win 7 Professional) it is working on IE 11 and Firefox 57, but not working on Chrome 64.

What do you mean by private navigation?

**Comment by cbliard** [comment]
Thanks for the information.

By private navigation, I mean opening a private window, like this:

![image](https://user-images.githubusercontent.com/176055/37389682-86b0df18-2765-11e8-8e78-5148c468a1e4.png)

It opens a fresh browser, without any extensions or existing cookies. Perfect to test if the issue occurs because of your browser configuration or because of a bug somewhere.

Speaking of that, it looks like there is a bug related to Chrome 64 and 65 on Windows that does not keep the sign-in state between chrome reboots: https://bugs.chromium.org/p/chromium/issues/detail?id=795827 Is it the behavior you are experiencing as well?

**Comment by christianbaumann** [comment]
Using private navigation, it works as intended.

Yes, the issue seems to be similar to the one linked by you.

Many thanks,
Christian

**Comment by christianbaumann** [comment]
@TimotheeVille May I ask why this issue has been closed without a solution being provided?

Thanks,
Christian

**Comment by TimotheeVille** [comment]
My bad, I think it was solved.

**Comment by aurelien-reeves** [comment]
Another user had an issue of that kind.
Actually that was due to an extension he used: Ghostery.

Indeed to remain logged-in you have to allow cookies both from Hiptest and Jira. That may be configured directly in the browsers privacy option, or via an extension like Ghostery.

@christianbaumann do you still encounter issues?

**Comment by christianbaumann** [comment]
Disabling Ghostery on Hiptest and Jira solved the issue, thanks for the hint!
